application_name: 'BTFoto'
seed_user_name: ''
seed_user_email: ''
seed_user_password: ''
application_creator: ''
gmail_email: ''
gmail_pass: ''
host: ''
discount_days: 20
freight_free: 580

gateway_uri: ''
owner_email: ''
agent_id: ''
hash: ""
return_uri: ''
shipping_fee: 33
prepaid_fee: 19
allowed_emails: ''

secret_token: ''