default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: btfoto_development

test:
  <<: *default
  database: btfoto_test

production:
  <<: *default
  host: db
  database: btfoto_production
  username: postgres
  password: <%= ENV['BT_FOTO_DATABASE_PASSWORD'] %>

